package top.iseason.bukkit.sakurabind.config

import top.iseason.bukkittemplate.config.annotations.Comment
import top.iseason.bukkittemplate.config.annotations.FilePath
import top.iseason.bukkittemplate.config.annotations.Key

@Key
@FilePath("lang.yml")
object Lang : top.iseason.bukkittemplate.config.Lang() {


    @Comment("", "物品送回消息, 占位符 {0} 是送回的物品数量")
    var send_back = ""
    var send_back__player_all = "&7你的{0}个遗失物品已全部放入你的&a背包"
    var send_back__player_half = "&7你的{0}个遗失物品放入你的&a背包"

    var send_back__ender_chest_all = "&7你的{0}个遗失物品已全部放入你的&a末影箱"
    var send_back__ender_chest_half = "&7你的{0}个遗失物品已放入你的&a末影箱"

    var send_back__database_all = "&7你的{0}个遗失物品已全部放入你的&a暂存箱"


    var item_bind_hand = "&7你手上的物品已绑定"
    var block_bind = "&7你前面的方块已绑定"
    var entity_bind = "&7你前面的实体已绑定"
    var item_bind_all = "&7你的背包物品已绑定"
    var item_unbind_hand = "&7你手上的物品已解绑"
    var block_unbind = "&7你前面的方块已解绑"
    var entity_unbind = "&7你手上的物品已解绑"
    var item_unbind_all = "&7你的背包物品已解绑"
    var entity_bind_on_spawner_egg = "&6你的生物已绑定!"

    var item__deny_command = "&6你不能拿着此物品输入该命令!"
    var item__deny_drop = "&6该物品不能丢出!"
    var item__deny_pickup = "&6该物品属于 &a{0},&6已归还"
    var item__deny_itemFrame = "&6该物品禁止放入展示框!"
    var item__deny_interact_left = "&6该物品禁止交互!"
    var item__deny_interact_right = "&6该物品禁止交互!"
    var item__deny_left_click_at_bind_block = "&6该物品禁止右键交互绑定方块!"
    var item__deny_right_click_at_bind_block = "&6该物品禁止右键交互绑定方块!"
    var item__deny_armor_stand_set = "&6该物品禁止放入盔甲架!"
    var item__deny_armor_stand_get = "&6该物品禁止从盔甲架取出!"
    var item__deny_entity_interact = "&6该物品禁止与实体交互!"
    var item__deny_click = "&6你不能拿走这个物品!"
    var item__deny_inventory = "&6此物品禁止放入这个容器!"
    var item__deny_throw = "&6该物品禁止投掷!"
    var item__deny_consume = "&6该物品禁止消耗!"
    var item__deny_craft = "&6该物品禁止用于合成!"
    var item__deny_anvil = "&6该物品禁止用于铁砧!"
    var item__deny_container_break = "&6该容器含有绑定物品，禁止破坏!"

    var auto_bind__onClick = "&a此物品已绑定你的灵魂!"
    var auto_bind__onPickup = "&a你捡到了与你相性最好的物品!"
    var auto_bind__onDrop = "&a你刚刚丢弃的物品将永远属于你!"
    var auto_bind__onScanner = "&a你背包有适合你的物品，已绑定你的灵魂!"
    var auto_bind__onUse = "&a此物品已绑定你的灵魂!"
    var auto_bind__onLeft = "&a此物品已绑定你的灵魂!"
    var auto_bind__onRight = "&a此物品已绑定你的灵魂!"
    var auto_bind__onEquiped = "&a你刚刚装备的物品已绑定"

    var auto_unbind__onClick = "&6此物品已解除绑定!"
    var auto_unbind__onPickup = "&6此物品已解除绑定!"
    var auto_unbind__onDrop = "&6此物品已解除绑定!"
    var auto_unbind__onScanner = "&6你背包的部分物品已解除绑定!"
    var auto_unbind__onUse = "&6此物品已解除绑定!"
    var auto_unbind__onLeft = "&6此物品已解除绑定!"
    var auto_unbind__onRight = "&6此物品已解除绑定!"
    var auto_unbind__onEquiped = "&6你刚刚装备的物品已解绑"

    var block__deny_break = "&6你不能破坏这个方块,这个方块属于 &b{0}"
    var block__deny_place = "&6你不能放置这个方块，此物物品已绑定"
    var block__deny_interact = "&6你没有这个方块的使用权限,这个方块属于 &b{0}"

    var entity__deny_damage = "&6你不能伤害这个实体，这个实体属于 &b{0}"
    var entity__deny_interact = "&6你没有这个实体的交互,这个实体属于 &b{0}"

    var scanner_item_send_back = "&6检测到你的背包存在别人的物品，已归还物主!"

    @Comment("", "命令消息")
    var command = ""
    var command__bind_item = "&a已绑定 &b{0} &a手上的物品"
    var command__bind_block = "&a已绑定 &b{0} &a前面的方块"
    var command__bind_entity = "&a已绑定 &b{0} &a前面的实体"
    var command__bindTo_item = "&a已将手上的物品绑定至 &b{0}"
    var command__bindTo_block = "&a已将前方的方块绑定至 &b{0}"
    var command__bindTo_entity = "&a已将前方的实体绑定至 &b{0}"
    var command__unbind_not_bind = "&6该目标并未绑定!"
    var command__unbind_item = "&a已将 &b{0} 手上的物品解绑"
    var command__unbind_block = "&a已将 &b{0} 前方的方块解绑"
    var command__unbind_entity = "&a已将 &b{0} 前方的实体解绑"
    var command__bindAll = "&a已绑定 &b{0} 整个背包的物品"
    var command__unbindAll = "&a已解绑 &b{0} 整个背包的物品"
    var command__getLost_item = "&a你领取了 &b{0} &a个遗失物品,请腾出空间领取剩余物品!"
    var command__getLost_empty = "&6没有遗失物品!"
    var command__getLost_full = "&6背包空间不足!"
    var command__getLost_all = "&a你领取了所有的遗失物品! 共 &b{0} &a个物品"
    var command__getLost_coolDown = "&6你输入得太快了!"
    var command__openLost_empty = "&6该玩家没有遗失的物品!"
    var command__openLost_page_not_exist = "&6没有这么多页,最多{0}页!"
    var command__openLost_open = "&6你打开了玩家 {0} 的暂存箱第 {1} 页"
    var command__openLost_closed = "&6玩家 {0} 暂存箱已更新"
    var command__select_on =
        "&a已经开启目标选择模式,右键选择 物品|方块|实体 \n&6输入/sakurabind select bind 确认绑定 \n&6再次输入命令取消选择"
    var command__select_off = "&6已经开启目标选择模式已关闭"
    var command__select_select_item = "&6你选择了手上的物品 {0} x {1}"
    var command__select_select_block = "&6你选择了点击的方块 {0} ({1},{2},{3})"
    var command__select_select_entity = "&6你选择了点击的实体 {0} ({1},{2},{3})"
    var command__select_has_bind = "&6该目标已经绑定，无法选择"
    var command__select_no_selected = "&6你没有选择目标!"
    var command__select_bind = "&6已绑定目标!"
    var command__select_timeout = "&6长时间未确认绑定，已退出选择模式!"
    var command__autoBind = "&a已添加 &b{0}"
    var command__test__match_start = "&6计划匹配物品 &b{0} &6次, 请等待..."
    var command__test__match = "&a匹配物品 &b{0} &a次, 设置为: &6{1} &7耗时: {2} 毫秒 / {3} 纳秒"
    var command__test__try_match_not_found = "&6该设置不存在"
    var command__test__try_match_header =
        "&4<--------使用设置 &6{0} &4匹配物品-------->\n&6  - [选项]: {模板} -> {物品内容} = {对比结果}"
    var command__test__try_match_name = "&a  - 名字: &f{0} -> &7{1} = &6{2}"
    var command__test__try_match_name_strip = "&a  - 名字(去色): &f{0} -> &7{1} = &6{2}"
    var command__test__try_match_lore = "&a  - Lore[{0}]: &f{1} -> &7{2} = &6{3}"
    var command__test__try_match_lore_strip = "&a  - 去色Lore[{0}]: &f{1} -> &7{2} = &6{3}"
    var command__test__try_match_material_pattern = "&a  - 材质正则: &f{0} -> &7{1} = &6{2}"
    var command__test__try_match_material_set = "&a  - 材质集合: &f{0} -> &7{1} = &6{2}"
    var command__test__try_match_material_id = "&a  - 材质:子ID: &f{0} -> &7{1} = &6{2}"
    var command__test__try_match_ids = "&a  - ID: &f{0} -> &7{1} = &6{2}"
    var command__test__try_match_nbt = "&a  - NBT: &f{0} -> &7{1} = &6{2} &7路径: {3}"
    var command__test__try_match_mmoitems = "&a  - MMOItems: &f{0} -> &7{1} = &6{2}"
    var command__test__try_match_itemsadder = "&a  - ItemsAdder: &f{0} -> &7{1} = &6{2}"
    var command__test__try_match_oraxen = "&a  - Oraxen: &f{0} -> &7{1} = &6{2}"
    var command__test__try_match_result = "&6匹配结束, 结果: &6{0}"
    var command__callback_on = "&a已开启物品召回模式，绑定您的物品将会陆续返回，再次输入命令关闭"
    var command__callback_off = "&6已关闭物品召回模式!"
    var command__callback = "&6该物品已被物主召回"
    var command__super_callback_start = "&7开始搜索 &6{0} &7的物品..."
    var command__super_callback_backpacks = "&7已搜索 &6{0} &7个玩家背包, 找到目标: &a{1} &7个, 耗时: &b{2} &7ms"
    var command__super_callback_sync = "&7已同步获取掉落物和容器数据, 耗时: &b{0} &7ms"
    var command__super_callback_drops = "&7已搜索 &6{0} &7个掉落物, 找到目标: &a{1} &7个, 耗时: &b{2} &7ms"
    var command__super_callback_containers = "&7已搜索 &6{0} &7个容器, 找到目标: &a{1} &7个, 耗时: &b{2} &7ms"
    var command__super_callback_end = "&a搜索结束, 已送回 &b{0} &a堆 共 &b{1} &a个物品, 耗时 {2} ms"
    var command__super_callback_player = "&a管理员为你找回了所有 &b{0} &a堆 共 &b{1} &a个绑定物品"
    var command__debug = "&aDebug模式: &b{0}"
    var command__debug_player_open = "&a已为开启玩家 {0} 的动作检查"
    var command__debug_player_close = "&a已关闭玩家 {0} 的动作检查"
    var has_lost_item = "&a你有遗失的物品,请输入 &6'/sakurabind getLost' &a领取"
    var lost_item_send_when_online = "&a你有遗失的物品,请输入 &6'/sakurabind getLost' &a领取"

    var bind_item__not_owner = "&6你不是这个物品的主人, 无法解绑"
    var bind_item__unbind_failure = "&6解绑失败"
    var bind_item__unbind_success = "&a解绑成功"
    var bind_item__bind_failure = "&6绑定失败"
    var bind_item__bind_success = "&a绑定成功"
    var bind_item__no_amount = "&6物品数量不足"

    var addons__mcmmo_salvage = "&6该物品无法分解"
    var addons__mcmmo_repair = "&6该物品无法修复"
    var addons__mcmmo_disarm = "&6该物品无法缴械"

}